# Generated by Django 4.2.7 on 2024-01-17 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woofers', '0002_veterinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinary',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='veterinary_pictures/'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('veterinary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woofers.veterinary')),
            ],
        ),
    ]
