# Generated by Django 4.2.7 on 2024-01-17 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woofers', '0003_veterinary_profile_picture_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='veterinary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='woofers.veterinary'),
        ),
    ]
