# Generated by Django 4.2.7 on 2024-02-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofers', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason_for_visit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
