# Generated by Django 4.2.7 on 2024-02-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woofers', '0009_user_profile_picture_veterinary_bio_alter_city_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinary',
            name='location',
        ),
    ]
