# Generated by Django 4.2.7 on 2024-03-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woofers', '0011_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
