# Generated by Django 4.2.7 on 2024-03-03 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woofers', '0012_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinary',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woofers.city'),
        ),
    ]
